### PR TITLE
1.0.0 RC2: Feature add ons, bugfixes, use low level VHCI control instead of Bluedroid or Nimble stack

### PR DESCRIPTION
**Pull request by cyberman54**

### CODE REVIEW

**Comment by cyberman54** [comment]
@FlorianLudwig I briefly checked scanning results with the lib in this VHCI direct command control version, against the former Bluedroid stack controlled version. Results are slightly better. Thus, i suggest to merge this PR now for v1.0.0.

**Comment by FlorianLudwig** [comment]
@cyberman54 
While it is an interesting experiment I would prefer to keep this code out of libpax as otherwise users of libpax might expect we maintain a low-level library for basic BLE functions. Sending advertisements is out of scope for libpax in my opinion.

So I would like to remove all unused functions.

/cc @oliverbrandmueller

**Comment by cyberman54** [comment]
ok, no problem. I can keep this in a separate branch in my fork repo, so nothing gets lost.

**Comment by FlorianLudwig** [comment]
@cyberman54 should I remove the code or will you update the MR?

**Comment by cyberman54** [comment]
I would prefer you do it, then i can leave my fork untouched to keep the code there. Thank you.

**Comment by cyberman54** [comment]
@FlorianLudwig i removed the advertising code from my branch HCI and this MR. Kept it in my new branch hci-advertise.

**Comment by oliverbrandmueller** [comment]
Code merged to master; 1.0 branch ahead

**Comment by torfo** [comment]
Hi @oliverbrandmueller Could you create a tag for the current version "1.0.0 RC2"?

**Comment by oliverbrandmueller** [comment]
@torfo We have a final fix pending (@FlorianLudwig is checking the default handling of counter mode) before releasing 1.0.0 which I would tag then.

**Comment by cyberman54** [comment]
@oliverbrandmueller is the final fix eta known?

**Comment by FlorianLudwig** [comment]
@cyberman54 There has been a report of crashes with the current master and a `1.0.0` release has to wait until that is cleared.

I am missing on details on the issue though so i have no eta.

**Comment by cyberman54** [comment]
can i get the report? I will take a look into, then.

**Pull request merged**
